- name: install dependencies...
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - python-pycurl

- name: Add the Treasuredata apt key
  apt_key: url=http://packages.treasuredata.com/GPG-KEY-td-agent state=present

- name: Add apt repository
  apt_repository: repo='deb [arch=amd64] http://packages.treasuredata.com/3/ubuntu/bionic/ bionic contrib' state=present

- name: install td-agent
  apt:
    name: td-agent
    state: latest

- name: mkdir direcrory
  file: path={{ item.path }} owner={{ item.owner }} group={{ item.group }} mode=0{{ item.mode }} state=directory
  with_items:
    - { "path":"/var/log/td-agent/buffer/", "owner":"td-agent", "group":"td-agent", "mode":"755" }
    - { "path":"/var/log/td-agent/s3/", "owner":"td-agent", "group":"td-agent", "mode":"755" }
    - { "path":"/var/log/td-agent/s3/nginx-logs/", "owner":"td-agent", "group":"td-agent", "mode":"755" }
    - { "path":"/etc/td-agent/conf.d", "owner":"td-agent", "group":"td-agent", "mode":"755" }

- name: put td-agent.conf
  template: src={{ item.src }} dest={{ item.dest }} owner={{ item.owner }} group={{ item.group }} mode=0{{ item.mode }}
  with_items:
    - { "src":"template/td-agent.conf.j2", "dest":"/etc/td-agent/td-agent.conf", "owner":"root", "group":"root", "mode":"644" }
    - { "src":"template/conf.d/nginx_match.conf.j2", "dest":"/etc/td-agent/conf.d/nginx_match.conf", "owner":"root", "group":"root", "mode":"644" }
    - { "src":"template/conf.d/nginx_source.conf.j2", "dest":"/etc/td-agent/conf.d/nginx_source.conf", "owner":"root", "group":"root", "mode":"644" }
    - { "src":"template/init.d/td-agent.j2", "dest":"/lib/systemd/system/td-agent.service", "owner":"root", "group":"root", "mode":"644" }
  notify:
    - reload td-agent

